---
- name: Add the OS specific variables
  include_vars: "{{ ansible_os_family }}.yml"
  tags: ["configuration","packages","service","ntp"]

- name: Install the required packages in {{ ansible_os_family }} derivatives
  package: name={{ item }} state={{ npt_pkg_state }}
  with_items:
    - "{{ ntp_pkgs }}"
  tags: ["packages","ntp"]

- name: Copy the Upstart ntpd.conf template file
  template: src=upstart_ntpd.conf.j2 dest=/etc/init/ntp.conf
  tags: ["Configuration","ntp"]
  when: ansible_service_mgr == "upstart"

- name: Copy the ntp.conf template file
  template: src=ntp.conf.j2 dest=/etc/ntp.conf
  notify: 
  - restart ntp
  tags: ["configuration","packages","ntp"]

- name: Start/stop ntp service
  service: name={{ ntp_service_name }} state={{ ntp_service_state }} enabled={{ ntp_service_enabled }} pattern="/ntpd"
  tags: ["service","ntp"]
